version: "3.8"

services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres/test7:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: app
    restart: always
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    environment:
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - $HOME/docker/volumes/test7:/var/lib