"""new fields in Users

Revision ID: 935564543605
Revises: a4f572a0d30b
Create Date: 2023-04-16 13:51:13.460546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935564543605'
down_revision = 'a4f572a0d30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hard_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('soft_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'soft_rate')
    op.drop_column('users', 'hard_rate')
    # ### end Alembic commands ###
